{% set name = "splot" %}
{% set version = "1.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/splot-{{ version }}.tar.gz
  sha256: 20d3c390a0b9aa130a5d6699f852c66f8c41e72f5ed14be0db59243c9ca430b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - descartes
    - esda
    - geopandas >=0.4.0
    - giddy
    - libpysal
    - mapclassify
    - matplotlib-base
    - numpy
    - seaborn
    - spreg
    # not listed in the metadata but required when importing splot.giddy
    - ipywidgets

test:
  imports:
    - splot
    - splot.esda
    - splot.giddy
    - splot.libpysal
    - splot.mapping
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Lightweight plotting and mapping to facilitate spatial analysis with PySAL

  description: |
    splot connects spatial analysis done in PySAL to different popular visualization
    toolkits like matplotlib. The splot package allows you to create both static plots
    ready for publication and interactive visualizations for quick iteration and
    spatial data exploration. The primary goal of splot is to enable you to visualize
    popular PySAL objects and gives you different views on your spatial analysis workflow.
  doc_url: https://splot.readthedocs.io/en/latest/
  dev_url: https://github.com/pysal/splot

extra:
  recipe-maintainers:
    - martinfleis
    - slumnitz
    - knaaptime
    - jGaboardi
