{% set name = "splot" %}
{% set version = "1.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/splot-{{ version }}.tar.gz
  sha256: 6edcaee24cd417965c378c5bc87414d02806915950c138c1f6e40f1a1de5286b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - esda
    - geopandas >=0.4.0
    - giddy
    - libpysal
    - mapclassify
    - matplotlib-base
    - numpy
    - seaborn
    - spreg
    # not listed in the metadata but required when importing splot.giddy
    - ipywidgets

test:
  imports:
    - splot
    - splot.esda
    - splot.giddy
    - splot.libpysal
    - splot.mapping
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Lightweight plotting and mapping to facilitate spatial analysis with PySAL

  description: |
    splot connects spatial analysis done in PySAL to different popular visualization
    toolkits like matplotlib. The splot package allows you to create both static plots
    ready for publication and interactive visualizations for quick iteration and
    spatial data exploration. The primary goal of splot is to enable you to visualize
    popular PySAL objects and gives you different views on your spatial analysis workflow.
  doc_url: https://splot.readthedocs.io/en/latest/
  dev_url: https://github.com/pysal/splot

extra:
  recipe-maintainers:
    - martinfleis
    - slumnitz
    - knaaptime
    - jGaboardi
